# Generated by Django 5.1.6 on 2025-02-26 16:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний ID покупателя')),
                ('tg_username', models.CharField(blank=True, max_length=50, verbose_name='Имя покупателя в Telegram')),
                ('first_name', models.CharField(blank=True, max_length=5, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('GDPR_status', models.BooleanField(default=False, null=True)),
                ('home_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Домашний адрес')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
    ]
