# Generated by Django 5.1.6 on 2025-02-26 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_bot', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя покупателя')),
                ('customer_chat_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Chat ID покупателя')),
                ('order_details', models.JSONField(default='Пока ничего нет', verbose_name='Детали заказа')),
                ('order_price', models.PositiveIntegerField(verbose_name='Цена заказа')),
                ('order_status', models.CharField(choices=[('Заявка обрабатывается', 'Заявка обрабатывается'), ('Готовим ваш торт', 'Готовим ваш торт'), ('Продукт в пути', 'Продукт в пути'), ('Продукт у вас', 'Продукт у вас')], default='Заявка обрабатывается', max_length=256, verbose_name='Статус заказа')),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарии')),
                ('delivery_address', models.CharField(default=' ', max_length=256, verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(blank=True, null=True, verbose_name='Время доставки')),
                ('order_type', models.CharField(choices=[('Собрать свой торт', 'Собрать свой торт'), ('Закзать торт', 'Заказать торт')], default='Закзать торт', max_length=17, verbose_name='Тип заказа')),
                ('cake_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake_bot.cake', verbose_name='Название торта')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product_properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake_bot.product')),
            ],
            options={
                'verbose_name': 'Свойства продукта',
                'verbose_name_plural': 'Свойства продуктов',
            },
        ),
        migrations.CreateModel(
            name='Product_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=256, verbose_name='Название параметра')),
                ('parameter_price', models.PositiveIntegerField(verbose_name='Цена')),
                ('product_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake_bot.product_properties', verbose_name='Свойства продукта')),
            ],
            options={
                'verbose_name': 'Параметры продукта',
                'verbose_name_plural': 'Парметры продуктов',
            },
        ),
    ]
