# Generated by Django 5.1.6 on 2025-03-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_bot', '0003_product_order_product_properties_product_parameters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Торт', 'verbose_name_plural': 'Торты'},
        ),
    ]
